services:
  - type: web
    name: hms-app
    runtime: python
    pythonVersion: 3.11.9

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        value: sqlite:///database.db

